### ISSUE TITLE
Feature request: implement link to QE or path-mode to STATE

### ISSUE THREAD

**Issue by uedar** [hhlim12/STATE-BATCH#52]
> However, the QE test failed in my environment.. (./pw.x not found error)
> QEbatch does not implement the `link` function to create a pw.x symbolic link in each directory, and `pw_loc` and `pw_name` in input.yaml does not seem to be used.
> Do you think we need to implement the link function in QE as well?

Yes this is an issue I'm not yet sure how to solve yet. This is actually more of a design problem. Usually in QE, we just use PATH to find the pw.x, in STATE it get's linked (though now I think there is already a way to use PATH). Shall we implement link to QE or path-mode to STATE ?

_Originally posted by @kimrojas in https://github.com/hhlim12/STATE-BATCH/pull/51#discussion_r1016211749_

**Comment by jdzla** [comment]
In my experience, the symbolic linking of pw.x works fine, albeit i'm not used to that. but if that is the case, you will still set the PATH to point to "./pw.x". I will double check this behavior but I think it is necessary to do path if we want to do the symlink.

**Comment by tbctan** [comment]
Is it also possible to declare the path as a variable, like PATH_TO_QE=/home/bctan/qe/bin/pw.x then call it as PATH_TO_QE input.pwi > output.pwo, then read the path from the dictionary?

**Comment by kimrojas** [comment]
> Is it also possible to declare the path as a variable in the job script, like PATH_TO_QE=/home/bctan/qe/bin/pw.x then call it as PATH_TO_QE input.pwi > output.pwo, then read the path from the dictionary?

It seems that the error we saw last meeting was because there is no "removesuffix" attribute in your python. apparently, its made available from 3.9, so maybe there is a version incompatibility. 

Moving forward, shall we update python version to 3.10? Since there are quite a lot of useful new features available (walrus operator, union operator, many new useful string attribute we can use). Its also mature enough at about 1 year old and its back-compatible so we can still use old code with this. @hhlim12 @uedar @tbctan @jdzla

**Comment by hhlim12** [comment]
I have no problem changing to python 3.10. It's already one version behind the latest (3.11) so I think OK.

**Comment by uedar** [comment]
Implemented  link function of pw.x in QEbatch https://github.com/hhlim12/STATE-BATCH/pull/63
Updating to python version 3.10 was also no problem.
